language: node_js

node_js: 
- "12"

services:
- docker

install:
- docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
- docker build -t tokenserversampleregistry.azurecr.io/tss tokenserversampleregistry.azurecr.io/tss

deploy: 
- provider: script
  on: 
    branch: master
  script: docker push tokenserversampleregistry.azurecr.io/tss